### ISSUE TITLE
Invalid station ID

### ISSUE THREAD

**Issue by jjanderson** [djtimca/handbc#1]
Hey,

Firstly, thanks for creating this, bummer about MagicSeaweed, but awesome that you have created this,

I am however coming across an issue.

When trying to add my station, I get the following screen on the UI

![image](https://user-images.githubusercontent.com/1214287/182130281-8c03d5cf-00ed-4018-8e96-39b99b95cdbc.png)

In checking the logs, I get this.

This is after simply selecting the station ID from the dropdown.

Quite possibly it is selecting the whole text as well as ID or visa versa.

I assume that hard coding it in somewhere my fix this, however wanted to bring this to your attention.

```
Logger: custom_components.ndbcrealtime.config_flow
Source: custom_components/ndbcrealtime/config_flow.py:34
Integration: NDBC Buoy Realtime Observation Data ([documentation](https://github.com/djtimca/handbc))
First occurred: 11:31:39 (3 occurrences)
Last logged: 11:33:40

Value Error: Invalid station ID (62027)
Traceback (most recent call last):
  File "/config/custom_components/ndbcrealtime/config_flow.py", line 34, in async_step_user
    observation = await ndbc.get_data()
  File "/usr/local/lib/python3.10/site-packages/ndbcrealtime/__init__.py", line 45, in get_data
    data = await self.get_json()
  File "/usr/local/lib/python3.10/site-packages/ndbcrealtime/__init__.py", line 213, in get_json
    raise ValueError(f"Invalid station ID ({self._station_id})")
ValueError: Invalid station ID (62027)
```

Thanks and let me know if I can help test.

**Comment by jjanderson** [comment]
I see that this is most probably caused by the station id closest to me not having received any data for the last 48Hrs... When I select another active station ID it is working....

Feel free to close this, thanks again for creating the component/
